
USE [master]
GO

/****** Object:  Database [VetClinic]    Script Date: 5/8/2017 7:45:30 AM ******/
CREATE DATABASE [VetClinic]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'VetClinic', FILENAME = N'C:\src\VetClinic.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'VetClinic_log', FILENAME = N'C:\src\VetClinic_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [VetClinic] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [VetClinic].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [VetClinic] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [VetClinic] SET ANSI_NULLS OFF
GO

ALTER DATABASE [VetClinic] SET ANSI_PADDING OFF
GO

ALTER DATABASE [VetClinic] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [VetClinic] SET ARITHABORT OFF
GO

ALTER DATABASE [VetClinic] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [VetClinic] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [VetClinic] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [VetClinic] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [VetClinic] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [VetClinic] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [VetClinic] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [VetClinic] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [VetClinic] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [VetClinic] SET  DISABLE_BROKER
GO

ALTER DATABASE [VetClinic] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [VetClinic] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [VetClinic] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [VetClinic] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [VetClinic] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [VetClinic] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [VetClinic] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [VetClinic] SET RECOVERY SIMPLE
GO

ALTER DATABASE [VetClinic] SET  MULTI_USER
GO

ALTER DATABASE [VetClinic] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [VetClinic] SET DB_CHAINING OFF
GO

ALTER DATABASE [VetClinic] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [VetClinic] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO

ALTER DATABASE [VetClinic] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [VetClinic] SET QUERY_STORE = OFF
GO

USE [VetClinic]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

USE [VetClinic]
GO

/****** Object:  Table [dbo].[Address]    Script Date: 5/8/2017 7:45:30 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Clinic]    Script Date: 5/8/2017 7:45:30 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Doctor]    Script Date: 5/8/2017 7:45:30 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[Patient]    Script Date: 5/8/2017 7:45:30 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  StoredProcedure [dbo].[AddAddress]    Script Date: 5/8/2017 7:45:30 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  StoredProcedure [dbo].[AddClinic]    Script Date: 5/8/2017 7:45:30 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  StoredProcedure [dbo].[AddDoctor]    Script Date: 5/8/2017 7:45:30 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  StoredProcedure [dbo].[AddPatients]    Script Date: 5/8/2017 7:45:30 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  StoredProcedure [dbo].[GetAddresses]    Script Date: 5/8/2017 7:45:30 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  StoredProcedure [dbo].[GetClinic]    Script Date: 5/8/2017 7:45:30 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  StoredProcedure [dbo].[GetDoctor]    Script Date: 5/8/2017 7:45:30 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  StoredProcedure [dbo].[GetPatients]    Script Date: 5/8/2017 7:45:30 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [master]
GO

ALTER DATABASE [VetClinic] SET  READ_WRITE
GO
